### ISSUE TITLE
Photoshop cannot open files

### ISSUE THREAD

**Issue by MegaByte** [google/guetzli#1]
Photoshop under OS X cannot open many files produced by guetzli. It returns with error "Could not complete your request because an invalid non-baseline JPEG table number >= 2 is found." I am also told that they don't work under OS X Preview for some people. I can run them through jpegtran to get them to work everywhere.

**Comment by robryk** [comment]
Can you provide an example of Guetzli output that demonstrates the Photoshop problem? Also, version of Photoshop you're using might be useful.

Do such files work for you in Preview (I'm not sure if they did work for you in Preview or if you didn't say either way)?

**Comment by MegaByte** [comment]
Source: ![tot_defaultpngsettings](https://cloud.githubusercontent.com/assets/202012/19737683/3dd974be-9b69-11e6-9356-13f6c66e561a.png)
Output: ![tot_guetzli_84](https://cloud.githubusercontent.com/assets/202012/19737532/b22403da-9b68-11e6-9ea5-ebe1e808b8a6.jpg)
Quality doesn't appear to matter -- I get the error with all qualities on this file (as well as others). I experienced the problem on Photoshop 2015.5 macOS 10.12.1. I did not have a problem in Finder. On the computer where Finder also didn't work, it was Photoshop 2015.5 and OS X 10.10.5.

**Comment by robryk** [comment]
I think I've found the issue. Would you mind verifing if the attached file can be opened in Photoshop?

File:
![image](https://cloud.githubusercontent.com/assets/1471395/19816962/c40a194e-9d49-11e6-8eec-34b6d1b273f7.jpg)

**Comment by MegaByte** [comment]
Yes, that file works for me.

**Comment by robryk** [comment]
Thanks. The commit I've just pushed should fix the problem.
