### ISSUE TITLE
Unable to compile in RHEL 6

### ISSUE THREAD

**Issue by jsEveryDay** [google/guetzli#108]
Works fine on CentOS 7 though.

`==== Building guetzli (release) ====
Creating bin/Release
Creating obj/Release
butteraugli_comparator.cc
cc1plus: error: unrecognized command line option "-std=c++11"
make[1]: *** [obj/Release/butteraugli_comparator.o] Error 1
make: *** [guetzli] Error 2
`

**Comment by robryk** [comment]
Please paste the output of `g++ -v`.

**Comment by gpant** [comment]
Centos 6.x comes with gcc-4.4.7 (specifically for an up to date system with 6.8 the package is gcc-4.4.7-17.el6) which doesnt support C++11.

**Comment by jsEveryDay** [comment]
Yes I knew it was a GCC versioning issue.
And of course the binary complied from RHEL 7 doesn't work on RHEL 6 due to gcc.

**Let's just leave it at CentOS 6 is not supported.**

FYI performance is horrible, this tool becomes quite useless.
Tested on CentOS 7 with 4 dual core CPU's and 48GB ram.
**1600kb jpg > 8 minutes > 1070kb JPG**

Can't beat tinypng.com
