### ISSUE TITLE
Document pkg-config build dependency

### ISSUE THREAD

**Issue by fkistner** [google/guetzli#110]
For example macOS does not come with `pkg-config` out of the box (though can easily be installed via Homebrew).
Might make sense to make this build dependency explicit in the README.

**Comment by robryk** [comment]
How does one go about finding library and include paths in absence of pkg-config? We can just use `pkg-config foobar || some-other-tool` in place of `pkg-config foobar`.

**Comment by pornel** [comment]
There's `libpng-config` tool, which is pretty much like libpng's own `pkg-config`.

However, there's nothing that works on macOS out of the box (all instances of libpng are in private frameworks).

**Comment by fkistner** [comment]
I can confirm that on my Sierra box 
`pkg-config --libs libpng` and `libpng-config --ldflags` as well as
`pkg-config --cflags libpng` and `libpng-config --cflags` provide identical results.

If you can implement the fallback to `libpng-config`, package managers would be able to remove the build dependency on `pkg-config`. The dependency on `libpng` is unaffected.
