### ISSUE TITLE
encode a png and use in AndroidStudio have an error

### ISSUE THREAD

**Issue by NoahZu** [google/guetzli#113]
Error:Execution failed for task ':app:merge Guanfang Debug Resources'. > Error: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException:

**Comment by cwh-github** [comment]
how to import guetzli into android studio?

**Comment by robryk** [comment]
@NoahZu The message you're posting should be longer (there should be something at the end of it). Could you post all of it?

@cwh-github I'm sadly unfamiliar with adding native libraries to Android projects.

**Comment by NoahZu** [comment]
ok,
1. I uset guetzli covert a bigger png image to smaller it's login_bg.png
2. in copy it to the mipmap-xxhdpi
3. I click Sync Project with Gradle Files
4. I get the log:
> Error:Execution failed for task ':app:mergeDebugResources'.
> Error: java.lang.RuntimeException: Crunching Cruncher login_bg.png failed, see logs
5. and then i check the detail logs, bug did not find associated log
thx for you solutions
@robryk

**Comment by robryk** [comment]
Guetzli creates JPEG files. If you save a Guetzli-created file with a `.png` extension, it will still be a JPEG file and it will confuse all the software that expects it to be a PNG file. I expect that using e.g. `login_bg.jpg` as the filename should help.

**Comment by NoahZu** [comment]
@robryk  thank you very much
