### ISSUE TITLE
Binary request

### ISSUE THREAD

**Issue by wetubeyou** [google/guetzli#117]
Please upload guetzli.exe for lazy people who can't use VC.

**Comment by robryk** [comment]
It's [already uploaded](https://github.com/google/guetzli/releases). How can I make it more visible?

**Comment by gpant** [comment]
Sorry for re oppening but you can always link the latest release in the readme.md using the release link, check https://help.github.com/articles/linking-to-releases/ for more info.

**Comment by robryk** [comment]
The problem is not lack of link, but apparent lack of discoverability of the link: there's already a link to the releases in the readme (grep for "download"), but apparently it's well hidden. I'd appreciate any suggestions about making it less well hidden.

**Comment by wetubeyou** [comment]
> To try out Guetzli you need to build or download the Guetzli binary. The binary reads a PNG or JPEG image and creates an optimized JPEG image:

Can you move "download" link to top?

to:

> Building
> If you can't build it yourself, [here's our release for easy use].

**Comment by wetubeyou** [comment]
- If you can't build it yourself, [here's our release for easy use].
+ If you can't build it yourself, [you can download our compiled release].

**Comment by wetubeyou** [comment]
ping @robryk @gpant
