### ISSUE TITLE
Travis Integration

### ISSUE THREAD

**Issue by gpant** [google/guetzli#126]
It would be nice if you could setup travis integration for the project, I already did that in my fork here: https://github.com/gpant/guetzli I don't want to create a PR since it would point to my own repo+travis account. 
You can just include the .travis.yml file and just add your project to https://travis-ci.org, it will build fine. If you check the change I made in README.md you will also find the link for build status image (you will need to change the URL).

Regards

**Comment by eustas** [comment]
Added basic build checks for Bazel.
More build systems to follow + appveyor + artifact pubishing...
