### ISSUE TITLE
Compare MOZJPG

### ISSUE THREAD

**Issue by pflacson** [google/guetzli#160]
I've found this : https://css-ig.net/articles/guetzli
MOZJPG compress more but quality is better with GUETZLI ?? I read GUETZLI has better compression.... or  it's because it's not the same quality ........ what settings should I use to get the best results ???
I would love to do testing too but.... I don't understand how to compare because DISSM is for 2 PNG !!!

"This tool computes (dis)similarity between two or more PNG images using an algorithm approximating human vision."
https://github.com/pornel/dssim
I've found for Windows :+1: https://kornel.ski/dssim
But I have a error : "not a PNG files" when I try JPGS !!!
Ok I found it.... It works if I convert JPGS to PNGS with Photoshop

**Comment by pornel** [comment]
There's an issue for this comparison: #10

**Comment by pflacson** [comment]
Sorry I did'nt see that ! Thank you very much for your very useful tool !!
