### ISSUE TITLE
double table[256] from gamma_correct.cc is not deleted

### ISSUE THREAD

**Issue by bluenlive** [google/guetzli#162]
**double table[256]** is created in **const double\* NewSrgb8ToLinearTable()** in **gamma_correct.cc**

`const double* NewSrgb8ToLinearTable() {`
`  double* table = new double[256];`
`  ...`
`}`

but, after being created, it is not deleted anywhere.

I think it should be changed to...

`const double* NewSrgb8ToLinearTable() {`
`  static double table[256];`
`  ...`
`}`

**Comment by robryk** [comment]
The caller owns the table. This function is called exactly once, and its return value is assigned to a static variable, thus the table will never become unreachable from the POV of a leak detector.

**Comment by bluenlive** [comment]
Ok, I understand your intension.

BTW, static library causes memory leak.
(Visual Studio 2017 / x86)

That's why I reported it.

Thanks.
