### ISSUE TITLE
Guetzli never ends when input is an empty file

### ISSUE THREAD

**Issue by jmespadero** [google/guetzli#166]
Guetzli process never ends when input is an empty file. The easiest way to test is...
```
touch empty.jpg
guetzli --verbose empty.jpg empty2.jpg
```

Of course, this is fault of the user who asked guetzli to compress a malformed JPG file, but it is a problem that can be frequent if is called in a script after the output of a program that has failed.

**Comment by robryk** [comment]
Thanks, this is indeed broken: we then try to read into a zero-length buffer.
