### ISSUE TITLE
Using guetzli -quality 84, ImageMagick identify -verbose reports Quality: 95

### ISSUE THREAD

**Issue by hguiney** [google/guetzli#172]
Using macOS Sierra 10.12.4.
ImageMagick 7.0.5-4 Q16 x86_64 2017-03-25

Is this expected behavior?

**Comment by pornel** [comment]
JPEG doesn't store actual quality value, but quantization tables, which are like 64 or 128 different quality settings for different levels of details.

So guessing single value back from qtables requires reverse engineering how they were made and guessing. ImagaMagick probably assumes the file was created with the stock libjpeg and gets confused when it sees more optimized file. ImageMagick is similarly confused by MozJPEG files.

**Comment by hguiney** [comment]
OK, thanks for the info!
