### ISSUE TITLE
is there any plan for support alpha channel (transparency) please?

### ISSUE THREAD

**Issue by csdnail** [google/guetzli#176]

**Comment by pornel** [comment]
Technically there's JPEG-XT now, which updated the old JPEG spec adding alpha channel in a backwards-compatible way, but none of the browsers "see" the alpha channel yet.

**Comment by Algae666** [comment]
Don't need JPG to end up transparent, but would be good to allow something other than black as the replacement color for transparent pixels.

**Comment by csdnail** [comment]
Meaningless for Android in most case. Thanks.
