### ISSUE TITLE
Anything like this planned for audio ?

### ISSUE THREAD

**Issue by boxerab** [google/guetzli#185]
For example, optimizing Opus for space.

**Comment by tomByrer** [comment]
MP3, Ogg, etc are psychoacoustic lossy compression for audio.
https://www.xaprb.com/blog/2016/02/21/best-itunes-mp3-format/

May I suggest this is out of scope?

**Comment by monouser7dig** [comment]
the main "issue" is that guetzli uses Butteraugli to achieve the quality and Butteraugli is it's quality measurement.

However, It is a quality measurement for images.
I don't think it works for audio.

You'd need such a thing for audio.

The main idea could probably be applied ti audio but yea seems somewhat out of scope...

**Comment by boxerab** [comment]
Alright, thanks for comments. Closing.
