### ISSUE TITLE
Build for Raspberry PI

### ISSUE THREAD

**Issue by rogierlommers** [google/guetzli#189]
I want to use the Guetzli binary on my raspberry PI cluster; but there is no compiled release for the ARM architecture available. Do you guys think it's possible to build Guetzli on ARM?

**Comment by szunyi** [comment]
I think the Raspberry Ram (1gb) can be small for this project. Or not?

**Comment by rogierlommers** [comment]
Don't know, but would love to try :). Unfortunately I don't know how to
compile for ARM.
Op ma 17 apr. 2017 om 09:11 schreef szunyi <notifications@github.com>

**Comment by fvm** [comment]
Would this be of any use perhaps? General approach for cross-compiling for ARM on Ubuntu (AMD64 - Ubuntu 12.04) https://askubuntu.com/questions/250696/cross-compile-for-arm#250721

**Comment by Furniel** [comment]
Cross compiled guetzli binary with [this toolchain](http://gnutoolchains.com/raspberry/). Not sure that it will work, but you can test:
[guetzli_raspberry.zip](https://github.com/google/guetzli/files/927563/guetzli_raspberry.zip)

**Comment by rogierlommers** [comment]
Thanks! Although it would be great if ARM builds are officially released :).
