### ISSUE TITLE
Can't read jpg data from input file

### ISSUE THREAD

**Issue by Fragger5000** [google/guetzli#19]
I'm trying to do something simple like this guetzli-master/bin/Release/guetzli --quality 84 /home/user/Desktop/logo.jpg /home/user/Desktop/logo.jpg

but I get this error

Can't read jpg data from input file
Guetzli processing failed

there are no problems with png to jpg , am I doing something wrong?

**Comment by robryk** [comment]
Providing the same file as input and output doesn't work. I will fix this problem shortly; in the meantime, please use different filenames.

**Comment by Fragger5000** [comment]
In fact I also tried to do guetzli-master/bin/Release/guetzli --quality 84 /home/user/Desktop/logo.jpg /home/user/Desktop/logo1.jpg 

but with the same result

**Comment by robryk** [comment]
I've split the other problem into a separate issue. Can you provide me a JPEG file on which it fails>

**Comment by Fragger5000** [comment]
forget it, my mistake, I used an empty file

**Comment by robryk** [comment]
Sorry, this is actually our fault, too. When Guetzli starts, it truncates the output file. So, the first time you've tried the input file got truncated. I'll close this issue and leave #20 for same input and output filename.

**Comment by amrendra-roy** [comment]
@Fragger5000 Photos capture by big camera like (DSLR) already compressed, Only uncompressed image can be use by Guetzli, so don’t use any images which is captured by this kind of device. For me Mobile images are working.

guetzli --quality 87kb original_Image_Page/origintal.PNG output_Image_Page_as_you_want/output_image_path.PNG
Note: Big size image will take more time.
