### ISSUE TITLE
Photoshop cannot open PNG-files

### ISSUE THREAD

**Issue by semi72** [google/guetzli#203]
I have a problem similar to [#1](https://github.com/google/guetzli/issues/1)  under OS X as well as Windows i cannot open a png-file produced by guetzli in Photoshop. It returns with the following error:

![error](https://cloud.githubusercontent.com/assets/2305860/25987547/c7d933d0-36f4-11e7-8ed0-7c6ca0450f17.png)

Adobe Photoshop Version: 2017.1.1 20170425.r.252

original:
![ps_test_original](https://cloud.githubusercontent.com/assets/2305860/25987370/ff078b00-36f3-11e7-97c7-35f68df6d3be.png)

optimized:
![ps_test_guetzli](https://cloud.githubusercontent.com/assets/2305860/25987375/07b0b0ba-36f4-11e7-86af-83072127f982.png)

**Comment by pornel** [comment]
Guetzli does not produce PNG files. It's a JPEG compressor. 

Please make sure you're using `.jpg` file extension for images produces by Guetzli.

**Comment by semi72** [comment]
@pornel Thank you for the clarification. 
I had overlooked that.
