### ISSUE TITLE
PGN with transparence turning full black jpg

### ISSUE THREAD

**Issue by RogerRussel** [google/guetzli#209]
Yo I tried compress this image with this "guetzli --quality 84 ok.png ok.jpg":
![ok](https://cloud.githubusercontent.com/assets/2228641/26592586/9419d40e-4537-11e7-9a99-b57c147e9866.png)

But it was compressed to a full black jpg
![ok](https://cloud.githubusercontent.com/assets/2228641/26592595/9770dd5a-4537-11e7-8e65-04e1a79085dd.jpg)

**Comment by romainmenke** [comment]
[README](https://github.com/google/guetzli#using)

> Please note that JPEG images do not support alpha channel (transparency). If the input is a PNG with an alpha channel, it will be overlaid on black background before encoding.

**Comment by RogerRussel** [comment]
I was expecting that would show a warning or error like when it show this: Only YUV color space input jpeg is supported
Guetzli processing failed
