### ISSUE TITLE
PNG output support?

### ISSUE THREAD

**Issue by toshimaru** [google/guetzli#22]
I'd like to create optimized PNG image.

Any plan to support PNG output? Or any recommended alternatives for PNG image?

**Comment by khavishbhundoo** [comment]
Guetzli is  a JPEG encoder and thus works only for JPEG images.Do you want only lossless optimization or even lossy would do ?

Lossy : pngquant
Lossless : optipng

**Comment by toshimaru** [comment]
> works only for JPEG images.

I got it!

Actually I was going to use `pngquant` for PNG images and I was wondering it'd be nice if guetzli could optimise both JPG and PNG.

Anyway, thank you :)
