### ISSUE TITLE
Is there any introduction about the real method of guetzl?

### ISSUE THREAD

**Issue by MrJiangSheng** [google/guetzli#222]
dear sir:
  I have learned most of JPEG encoder,but many detil of guatzli is difficult to understand.Is there any introduction about the jpeg encoder?
  thanks very much.

**Comment by jyrkialakuijala** [comment]
https://arxiv.org/abs/1703.04421 is a rough description

There is a selection of the quantization matrix (global optimization), and then performing the actual quantization (iterative local optimization).
