### ISSUE TITLE
Cannot run guetzli after build

### ISSUE THREAD

**Issue by mwizasimbeye11** [google/guetzli#225]
I just got the latest guetzli release, and I have been trying to run it on my Ubuntu 17.04, I used the installation instructions from the README.md file, however, even after the successful build it keeps saying: **guetzli: command not found**
Also there is no file created in **bin/Release/**
Please help.

**Comment by mwizasimbeye11** [comment]
Fixed!

**Comment by Stasevi4** [comment]
How did you fix it ?

**Comment by mwizasimbeye11** [comment]
Ran the program with sudo.

**Comment by Stasevi4** [comment]
No same result "sudo: guetzli: command not found"

**Comment by mwizasimbeye11** [comment]
Check the bin folder in guetzli, then cd to Release, you should find guetzli

**Comment by Stasevi4** [comment]
Yes i have it 
guetzli/bin/Release$ ls
guetzli  libguetzli_static.a

**Comment by mwizasimbeye11** [comment]
Now ran guetzli, with ./guetzli

**Comment by Stasevi4** [comment]
Thank you

**Comment by mwizasimbeye11** [comment]
You are welcome
