### ISSUE TITLE
An inquiry about the maximum size a Guetzli image

### ISSUE THREAD

**Issue by amughrabi** [google/guetzli#244]
I wish to have an answer about the maximum pixel dimensions of a Guetzli image; for instance, what is the maximum image width and height (W x H) for the source image before calling it via command line?

**Comment by kornelski** [comment]
Probably the same as limits of JPEG in general (65kx65k), but it will require 1200GB of memory and take 70 hours to compress.

**Comment by amughrabi** [comment]
> but it will require 1200GB of memory and take 70 hours to compress.

Oh, this totally will kill the server in terms the server do some processes in parallel. For the Web development, I feel 16383 x 16383 pixels as Webp definition will be good: https://developers.google.com/speed/webp/faq#what_is_the_maximum_size_a_webp_image_can_be

**Comment by kornelski** [comment]
Minimum is 1x1. Smallest that makes sense is 8x8.

**Comment by amughrabi** [comment]
Yes, it makes sense! Thanks, @kornelski!
