### ISSUE TITLE
sRGB vs gamma

### ISSUE THREAD

**Issue by develancer** [google/guetzli#259]
The documentation states:
> Guetzli assumes that input is in sRGB profile with a gamma of 2.2.

The problem is that sRGB does not use gamma of 2.2, but rather a more complicated transformation: linear for near-black, and scaled gamma of 2.4 otherwise.

So which one it is then? Transform according to sRGB standard, or constant gamma of 2.2?

**Comment by jyrkialakuijala** [comment]
https://github.com/google/guetzli/blob/master/guetzli/gamma_correct.cc

i.e., real sRGB, and not constant gamma of 2.2 is what has been implemented

**Comment by develancer** [comment]
@jyrkialakuijala Great, thanks!
It may be a good idea to fix the README at some point.
