### ISSUE TITLE
Building on OS X

### ISSUE THREAD

**Issue by dalanmiller** [google/guetzli#39]
```
$ ~ brew list
... gflags libpng ... 
$ ~/git/guetzli make
==== Building guetzli (release) ====
guetzli.cc
guetzli/guetzli.cc:24:10: fatal error: 'gflags/gflags.h' file not found
#include "gflags/gflags.h"
         ^
1 error generated.
make[1]: *** [obj/Release/guetzli.o] Error 1
make: *** [guetzli] Error 2 
```

Anyone gotten this to work?

**Comment by btnwtn** [comment]
Try `brew update && brew install libpng gflags`.

**Comment by dalanmiller** [comment]
```
$ ~ brew update && brew install libpng gflags
Already up-to-date.
Warning: libpng-1.6.28 already installed
Warning: gflags-2.2.0 already installed
```

**Comment by dalanmiller** [comment]
I think it might be something to do with the way `gflags` is linked? I've done both `brew unlink` and `brew link` on it however.

**Comment by pornel** [comment]
```sh
 brew unlink gflags && brew link gflags
```

doesn't help.

It's not a link error though. It's missing include path.

**Comment by bscottx** [comment]
I downloaded and unpacked the archive and then CLI'd into the unpacked folder and ran `make` and it worked just fine. This is after doing `brew update && brew install libpng gflags`

**Comment by CliffsDover** [comment]
Add path to headers and the libraries guetzli.make will solve your problem.
Because Homebrew will install headers and libraries to /usr/local/include and /usr/local/lib by default.

**Comment by fkistner** [comment]
See also: Homebrew/homebrew-core#11190 (seems to work fine for El Capitan and Sierra)

**Comment by bcackerman** [comment]
Someone's gotta make a simple app around this

**Comment by pornel** [comment]
I'll be adding it to [ImageOptim](https://github.com/ImageOptim/ImageOptim/issues/194).

**Comment by positlabs** [comment]
Nice. I was just about to suggest that!

**Comment by gcomstock** [comment]
Thanks @pornel ! I'm excited to share this with our design team.

**Comment by Pesthauch666** [comment]
BTW if someone is planning to built it with libpng gflags installed via **MacPorts** you have to edit _guetzli.make_ similar as CliffsDovers suggestion above. But for MacPorts it has to point to /opt/local/lib

In both lines beginning wie LIBS you have to add:
` -L/opt/local/lib`
like   `LIBS += -L/opt/local/lib -lpng -lgflags_nothreads -lz -lpthread`

**Comment by robryk** [comment]
@Pesthauch666 Does MacPorts cause `pkg-config` to report correct paths?

**Comment by Pesthauch666** [comment]
@robryk
I'm not that familar with this tool (I'm still a rookie after all), but:
`pkg-config --libs libpng`
reports
`-L/opt/local/lib -lpng16`
