### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by JoeArizona** [google/guetzli#4]
The only binaries are for Linux and Mac. Do you plan to support Windows? If so, when do you expect Windows binaries to be available?

**Comment by robryk** [comment]
Changed required to get this to build on Windows will be merged soon (#5). When that happens, I will publish a new set of binaries, including Windows binaries.

In the meantime, [Windows binary compiled from that pull request](https://github.com/google/guetzli/files/664934/guetzli-windows-x86.zip) is attached (in a zip file, together with necessary DLLs).

**Comment by robryk** [comment]
I've just published [a release with Windows binaries](https://github.com/google/guetzli/releases/tag/v0.1).

**Comment by JoeArizona** [comment]
Hey thanks Robert. That was fast.

**Comment by gimigliano** [comment]
Thank you but crashes on windows 10, some idea?

**Comment by robryk** [comment]
@gimigliano I've just fixed a crash with #23. Was your crash fixed by that PR too?

**Comment by gimigliano** [comment]
Please update binaries
