### ISSUE TITLE
Unbelievably good encoding performance?

### ISSUE THREAD

**Issue by Smilebags** [google/guetzli#65]
It seems unrealistic, but testing on 128px square images at 90 quality, I'm getting roughly 10x smaller files than PS saving the same images at 9 quality. Visual quality is comparable.

I've written a blog post showing the results and will attach a zip of the results later.
http://uxgroup.com.au/using-googles-guetzli-jpeg-encoder

This isn't a bug, but I want to know what factor is resulting in this performance, as it doesn't seem to be normal.

**Comment by pornel** [comment]
Photoshop adds a lot of unnecessary large metadata to saved files, especially if you use color profiles. 

Use a JPEG optimizer first (jpegoptim, imageoptim) or at least only use "Save for Web" (without embedded profiles, converted to sRGB) for generating JPEGs from Photoshop when file size matters.

**Comment by Smilebags** [comment]
Thanks for the explanation. I had a feeling something like that was going on. That helps clear it up.

**Comment by hazarkarabay** [comment]
Adobe Photoshop has "Save for Web" feature that strips metadata and gives finer control on its output.

**Comment by robryk** [comment]
It was likely the color profile information that Guetzli dropped. Guetzli, by default, preserves e.g. all [application-specific markers](https://github.com/google/guetzli/blob/b473cf61275991e2a937fe0402d28538b342d2f8/guetzli/jpeg_data_reader.cc#L996).
