### ISSUE TITLE
What happens when guetzli optimized images are optimized by guetzli again

### ISSUE THREAD

**Issue by syeo66** [google/guetzli#69]
Does it detect it, is the quality unaffected or should I avoid it (as the manual states about using guetzli on images optimized by other optimizers)?

Maybe something to add to the manual.

**Comment by robryk** [comment]
You should avoid it. I will make sure it's clearer in the README.

**Comment by Smilebags** [comment]
The thing with jpeg is that the best case you could possibly get is 'just a bit worse than the input'. Optimizing something twice will result in less detail, and maybe a marginally smaller file, but the gains will be insignificant. Probably good to just avoid it.

**Comment by syeo66** [comment]
Thanks. Well, it's just good to know when having some automated optimizing included in your deployment process.
