### ISSUE TITLE
Compressing following small jpg file caused program to crash

### ISSUE THREAD

**Issue by xqiu** [google/guetzli#81]
![scrollbackground](https://cloud.githubusercontent.com/assets/1487053/24080731/d6ec28d0-0cdf-11e7-9f68-7afba34aace3.jpg)

The command I used is:
guetzli_windows_x86-64.exe --quality 100 file.jpg output.jpg

**Comment by robryk** [comment]
This is the same as #38, there was just no release since then.

**Comment by robryk** [comment]
[Release 1.0.1](https://github.com/google/guetzli/releases/tag/v1.0.1) has this issue fixed. Please reopen if that release is broken.
