### ISSUE TITLE
Compiliation problem on macOS Sierra with MacPorts

### ISSUE THREAD

**Issue by afiller** [google/guetzli#91]
When I try to build it based on your tutorial with my Mac (newest OS, newest MacPorts version) I get the following error:

```
==== Building guetzli (release) ====
guetzli.cc
Package gflags was not found in the pkg-config search path.
Perhaps you should add the directory containing `gflags.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gflags' found
guetzli/guetzli.cc:23:10: fatal error: 'gflags/gflags.h' file not found
#include "gflags/gflags.h"
         ^
1 error generated.
make[1]: *** [obj/Release/guetzli.o] Error 1
make: *** [guetzli] Error 2
```

Any ideas how to solve this?

**Comment by GuillaumeSTEIN** [comment]
Why don't you "brew install guetzli" ? [homebrew](https://brew.sh/)

**Comment by afiller** [comment]
Because I prefer MacPorts and the tutorial says, that it should work with with it as well. - I also tried out the precompiled binary, but OS communities are there to learn from each other, right? :-)

**Comment by GuillaumeSTEIN** [comment]
ok, I understand.
Sorry I used brew, can't help you.

**Comment by robryk** [comment]
#97 removes the dependency on gflags. Please update to the current version, try again, and reopen if problems persist. Sorry for the trouble.
