### ISSUE TITLE
Result by guetzli: 1.3mb image compressed to 692.7kb. With Microsoft Paint, 1.3mb image compressed to 792kb.

### ISSUE THREAD

**Issue by rdp-in** [google/guetzli#93]
Hi,

I just tried this tool and its great. As in, does the job.
But when I showed it to a friend of mine, he  compressed the same image using Microsoft paint and got a similar result.

So, I'm just wondering how this tool is different and better than the other tools available out there?
Also, the time taken by Paint is much less than the time taken by Guetzli.

Is there anyone else who share a similar opinion?

**Comment by mikesmiffy128** [comment]
Well, assuming I haven't messed up the maths, that's a 12.5% reduction in size from Paint. There's definitely a difference. Obviously for smaller files it might not be worth the time though. But also, you probably want them to be equal in size in order to compare quality. Rendering two random files doesn't give much of a comparison.

**Comment by rdp-in** [comment]
I understand that but how do you determine which tool gives a better quality in image after compression?

**Comment by mikesmiffy128** [comment]
Look at it. ☺️

**Comment by rdp-in** [comment]
Lol cool. Just want to know what other people think about this tool.
Also @mikesmiffy128 what are your opinions about it?
Was all the effort put down to make this tool worth?

**Comment by saurabheights** [comment]
@rdp-in : This might provide you more context: https://research.googleblog.com/2017/03/announcing-guetzli-new-open-source-jpeg.html . Also, notice metrics on SSIM and butteraugli. P.S. These metrics though work, are not reliable for every case, so testing on one image is not very helpful.

**Comment by rdp-in** [comment]
@saurabheights : Thanks for the link, even though before using this tool I did went through it. And unlike you I'm not much of an image guy so din't know about SSIM not butteraugli. But thanks.
Will try to experiment a little bit more on this.
