### ISSUE TITLE
Cause the Homebrew build to use newer source

### ISSUE THREAD

**Issue by tliesnham** [google/guetzli#95]
I'm using the Guetzli build with Homebrew. When compressing smaller images I'm getting a segmentation fault. The file in question is 419 bytes, and can be found at [https://www.coastercms.org/themes/coaster/img/line.jpg](url).

**Comment by robryk** [comment]
This has been fixed by #51, but the Homebrew build has to be updated yet.

**Comment by fkistner** [comment]
@robryk Can you create a bugfix release for guetzli, e.g. 1.0.1?
Then we can bump the guetzli homebrew Formula to that.

**Comment by robryk** [comment]
@fkistner I was just doing it. Here it is: https://github.com/google/guetzli/releases/tag/v1.0.1

I would very much appreciate if you made the appropriate modifications to the Homebrew formula.

**Comment by fkistner** [comment]
@robryk On its way: Homebrew/homebrew-core#11428

**Comment by fkistner** [comment]
Resolved in Homebrew/homebrew-core@837d78f79437fca5855cb7a013e5f9f9c48684b9.
Now also available on Yosemite.

**Comment by tliesnham** [comment]
Thanks @robryk and @fkistner it's now working perfectly.
