### ISSUE TITLE
Incredibly slow?

### ISSUE THREAD

**Issue by k0nr4d** [google/guetzli#96]
I just ran this on a test image. 7mbyte photo of my car taken with a LG G4 phone - nothing special.
I did two benchmarks, one with jpegoptim, one with guetzli. 

JPEGOPTIM: 7100008 bytes -> 3306762 bytes (less then 1 second)
GUETZLI: 7100008 bytes -> 4652672 bytes (approx 52 minutes)

Completely ignoring the fact that the end result was larger then jpegoptim, it took - Yes - *52 minutes* to process the image on a relatively fast desktop pc.  It was working the entire time, I had it on verbose mode. 

Guetzli was run under Windows 7 64bit, jpegoptim under CentOS 6.

Did I do something wrong or is everyone getting results like this?

**Comment by pornel** [comment]
It's expected to be that slow: #50
