### ISSUE TITLE
Man files missing

### ISSUE THREAD

**Issue by fmunteanu** [google/guetzli#98]
Hi,

I created the rpm package for CentOS7:
```
$ sudo yum install http://rpm.axivo.com/axivo-release-7-1.noarch.rpm
$ sudo yum --enablerepo=axivo install guetzli
$ yum -q info guetzli
Installed Packages
Name        : guetzli
Arch        : x86_64
Version     : 1.0
Release     : 1.el7
Size        : 473 k
Repo        : installed
From repo   : axivo
Summary     : Perceptual JPEG encoder
URL         : https://github.com/google/guetzli
License     : ASL 2.0
Description : Guetzli is a JPEG encoder that aims for excellent compression density at high
            : visual quality. Guetzli-generated images are typically 20-30% smaller than
            : images of equivalent quality generated by libjpeg. Guetzli generates only
            : sequential (nonprogressive) JPEGs due to faster decompression speeds they offer.
```
The man files are missing for guetzli and butteraugli, I was wondering if I missed something into make:
```
$ rpm -ql guetzli
/usr/bin/butteraugli
/usr/bin/guetzli
/usr/share/doc/guetzli-1.0
/usr/share/doc/guetzli-1.0/LICENSE
/usr/share/doc/guetzli-1.0/README.md
```
Regards,

Floren Munteanu

**Comment by robryk** [comment]
You did everything correctly. They are currently missing. Let's use this issue as a feature request for the manpages.

**Comment by dvershinin** [comment]
An RPM package with man page from [here](http://manpages.ubuntu.com/manpages/bionic/man1/guetzli.1.html) is available for RHEL/CentOS 7 and 8:

    sudo yum -y install https://extras.getpagespeed.com/release-latest.rpm
    sudo yum -y install guetzli

For comparison script, will install butteraugli dependency:

    sudo yum -y installl guetzli-compare 

Package sources [here](https://github.com/GetPageSpeed/guetzli-rpm)

**Comment by kstahl-dev** [comment]
> An RPM package with man page from [here](http://manpages.ubuntu.com/manpages/bionic/man1/guetzli.1.html) is available for RHEL/CentOS 7 and 8:
> 
> ```
> yum install https://extras.getpagespeed.com/release-el$(rpm -E %{rhel})-latest.rpm
> yum install guetzli
> ```
> 
> For comparison script, will install butteraugli dependency:
> 
> ```
> yum installl guetzli-compare 
> ```
> 
> Package sources [here](https://github.com/GetPageSpeed/guetzli-rpm)

I tried to use the rpm you suggested, it didnt work. Now Im having a big trouble to uninstall it from the server (centOS7) . 

Tried rpm -ev  e yum remove and only get errors.

I believe the package is broken or missing some files...How can I uninstall it?

**Comment by dvershinin** [comment]
If you watched the installation process carefully, you would notice that installing the packages from the repository requires a subscription.

Obviously, `rpm` has not much idea on how you installed it. 

    rpm -ev e yum

That would uninstall `yum`. What are you really trying to do?

**Comment by kstahl-dev** [comment]
Hi,

Yes, I noticed the subscription, which is U$10.00/month. That's why I decided to uninstall it instead of subscribing.

I installed using the step by step 

Install GetPageSpeed repository:
# yum install https://extras.getpagespeed.com/release-el7-latest.rpm

So really just would like to remove it from my server...

**Comment by dvershinin** [comment]
If you didn't subscribe, it means you didn't install guetzli package. So then there's literally nothing left to uninstall other than the release package:

    yum remove getpagespeed-extras-release
